export const sample_foods = [
  {
    id: '1',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '8',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '9',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '10',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '11',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '12',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '13',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '14',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '15',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '16',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '17',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '18',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '19',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '20',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '21',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '22',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '23',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '24',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '25',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '26',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '27',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '28',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '29',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '30',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '31',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '32',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '33',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '34',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '35',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '36',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '37',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '38',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '39',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '40',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '41',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '42',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '43',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '44',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '45',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '46',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '47',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '48',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '49',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '50',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '51',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '52',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '53',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '54',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '55',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '56',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '57',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '58',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '59',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '60',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '61',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '62',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '63',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '64',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '65',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '66',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '67',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '68',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '69',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '70',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '71',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '72',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '73',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '74',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '75',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '76',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '77',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '78',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '79',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '80',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '81',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '82',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '83',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '84',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '85',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '86',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '87',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '88',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '89',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '90',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '91',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '92',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '93',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '94',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '95',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '96',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '97',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '98',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '99',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '100',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '101',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '102',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '103',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '104',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '105',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '106',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '107',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '108',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '109',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '110',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '111',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '112',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '113',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '114',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '115',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '116',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '117',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '118',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '119',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '120',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '121',
    name: 'Pepperoni Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244755/nrxky5zwdrnfg4vkujyx.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '122',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244876/alwnzwfp6uo7rnyq5tsm.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '123',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245050/zft9ca3gjdrewcn5uryc.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '124',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245144/h7f8tdoeqatrsfzjr8pj.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '125',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727245090/scl8tb0dk9igbbb9rccl.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '126',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'http://res.cloudinary.com/dmprsl1mx/image/upload/v1727244976/nhah21pc1aglejs7unvg.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
